[package]
edition = "2024"
name = "volatix_cli"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
bincode2.workspace = true
crossterm = { workspace = true }
serde.workspace = true
volatix_core = { workspace = true }
