[package]
edition = "2024"
name = "volatix_server"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ctrlc.workspace = true
parking_lot = { workspace = true }
volatix_core = { workspace = true }
